openapi: "3.0.0"
info:
  title: My API
  version: 1.0.0
  description: This is a sample API.
paths:
  /upload:
    post:
      summary: Uploads an image file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: "Uploading success"
          content:
            text/plain:
              schema:
                type: string
      security:
        - jwt: [ 'secret' ]
  /login:
    get:
      summary: Return JWT token
      parameters:
        - name: username
          description: Username
          in: query
          required: true
          schema:
            type: string
        - name: password
          description: User password
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: JWT token
          content:
            'text/plain':
              schema:
                type: string
  /register:
    get:
      summary: Register user and return JWT token
      parameters:
        - name: username
          description: Username
          in: query
          required: true
          schema:
            type: string
        - name: password
          description: User password
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: JWT token
          content:
            'text/plain':
              schema:
                type: string
  /refreshToken:
    get:
      summary: Get new JWT token for this device
      responses:
        200:
          description: "Refreshing token success"
          content:
            text/plain:
              schema:
                type: string
      security:
        - jwt: [ 'secret' ]
  /secret:
    get:
      summary: Return secret string
      responses:
        '200':
          description: secret response
          content:
            'text/plain':
              schema:
                type: string
      security:
        - jwt: [ 'secret' ]
components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: classes.user.decode_token